### ISSUE TITLE
Exception when recovering form Expansion Hub coms reset

### ISSUE THREAD

**Issue by gearsincorg** [OpenFTC/RevExtensions2#6] opened 2019-02-28 16:46 UTC
I'm using REVExtensions to speed up encoder reads on my two expansion hubs.

Occasionally I get an exception which appears to think it's a SDK mismatch, but clearly it's more than that.

When I get an expansion hub USB timeout that disconnects and then reconnects while my Teleop is running, I get the following exception:

RE2Exception - Failed to reflect on LynxController! This probably means that you're running a newer version of the SDK then I tested with and the Tech Team broke something :(

When I step beyond the dig at my team, I suppose that there must be some transitory period where the interface returns an invalid object that is being treated as an exception....

Is there a clean way to detect/recover from this?  
Notice the dropout after 4 minutes of running teleop...
The system hickups and appears to recover, but the module attach then triggers the exception.
see 16:55:49.535

```


-27 16:51:19.191 10131 10211 V Robocol : received command: CMD_RUN_OP_MODE(13173) 2818 TELEOP
02-27 16:51:19.241 10131 10216 V Robocol : sending CMD_NOTIFY_RUN_OP_MODE(3468), attempt: 0
02-27 16:55:46.170 10131 10374 V LynxModule: retransmitting: mod=3 cmd=0x1000 msg#=101 ref#=0 
02-27 16:55:46.372 10131 10214 E MonitoredUsbDeviceConnection: watchdog: stuck USB write(11 bytes) threadId=847 TID=10374:: serial=DQ15NX6V closing device
02-27 16:55:46.373 10131 10214 V FtDevice: vv********************DQ15NX6V closing********************vv 0x02d0f205
02-27 16:55:46.373 10131 10214 V FtDevice: DQ15NX6V stopping thread readBufferManager
02-27 16:55:46.374 10131 10213 V FtDevice: DQ15NX6V thread readBufferManager is stopped
02-27 16:55:46.375 10131 10214 V FtDevice: DQ15NX6V stopping thread bulkPacketInWorker
02-27 16:55:46.375 10131 10229 V RobotCore: event loop: device has shutdown abnormally: ABNORMAL
02-27 16:55:46.376 10131 10229 V EventLoopManager: event loop: detaching device DQ15NX6V
02-27 16:55:46.376 10131 10229 I FtcEventLoop: vv===== MODULE DETACH RECOVERY: disarm REV Robotics USB Expansion Hub Portal [DQ15NX6V]=====vv
02-27 16:55:46.381 10131 10229 V LynxUsb : disarmDevice() serial=DQ15NX6V...
02-27 16:55:46.383 10131 10215 V RobotCore: thread: ...terminating 'lynx incoming datagrams'
02-27 16:55:46.383 10131 10229 V LynxUsb : shutting down incoming datagrams
02-27 16:55:46.386 10131 10229 V RobotUsbDeviceFtdi: closing DQ15NX6V
02-27 16:55:47.420 10131 10214 V MonitoredUsbDeviceConnection: closing UsbDeviceConnection(DQ15NX6V)
02-27 16:55:47.421 10131 10214 D UsbDeviceConnectionJNI: close
02-27 16:55:47.421 10131 10214 V FtDevice: ^^********************DQ15NX6V closed ********************^^
02-27 16:55:47.422 10131 10229 V LynxUsb : ...done disarmDevice()
02-27 16:55:47.422 10131 10212 E BulkPacketInWorker: DQ15NX6V: bulkTransfer() error: -1
02-27 16:55:47.423 10131 10212 V FtDevice: DQ15NX6V thread bulkPacketInWorker is stopped
02-27 16:55:47.423 10131 10229 I FtcEventLoop: ======= MODULE DETACH RECOVERY: pretend REV Robotics USB Expansion Hub Portal [DQ15NX6V]=======
02-27 16:55:47.424 10131 10374 E RobotCore: lynx xmit lock: #### releasing ownerless message keyed lock: ignored: LynxGetBulkInputDataCommand
02-27 16:55:47.424 10131 10374 E RobotCore: exception thrown during lynx communication
02-27 16:55:47.425 10131 10229 V LynxUsb : doPretend() serial=DQ15NX6V
02-27 16:55:47.427 10131 10229 I FtcEventLoop: ^^===== MODULE DETACH RECOVERY: complete REV Robotics USB Expansion Hub Portal [DQ15NX6V]=====^^
02-27 16:55:47.433 10131 10374 E RobotCore: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.qualcomm.robotcore.hardware.usb.RobotUsbDevice.isAttached()' on a null object reference
02-27 16:55:47.436 10131 10374 E RobotCore: 	at com.qualcomm.hardware.lynx.LynxUsbDeviceImpl.shutdownAbnormally(LynxUsbDeviceImpl.java:827)
02-27 16:55:47.438 10131 10374 E RobotCore: 	at com.qualcomm.hardware.lynx.LynxUsbDeviceImpl.transmit(LynxUsbDeviceImpl.java:793)
02-27 16:55:47.440 10131 10374 E RobotCore: 	at com.qualcomm.hardware.lynx.LynxUsbDeviceDelegate.transmit(LynxUsbDeviceDelegate.java:192)
02-27 16:55:47.441 10131 10229 D RobotCore: system telemetry: key=$System$Warning$ msg="problem with "Expansion Hub DC Motor Controller [USB DQ15NX6V; module 3]"; problem with "Expansion Hub Servo Controller [USB DQ15NX6V; module 3]"; problem with "Expansion Hub Voltage Sensor [USB DQ15NX6V; module 3]"; problem with "Expansion Hub Pwm Controller [USB DQ15NX6V; module 3]"; problem with "Expansion Hub Analog Input Controller [USB DQ15NX6V; module 3]"; problem with "Expansion Hub Digital Channel Controller [USB DQ15NX6V; module 3]"; problem with "imu"; problem with "Expansion Hub DC Motor Controller [USB DQ15NX6V; module 4]"; problem with "Expansion Hub Servo Controller [USB DQ15NX6V; module 4]"; problem with "Expansion Hub Voltage Sensor [USB DQ15NX6V; module 4]"; problem with "Expansion Hub Pwm Controller [USB DQ15NX6V; module 4]"; problem with "Expansion Hub Analog Input Controller [USB DQ15NX6V; module 4]"; problem with "Expansion Hub Digital Channel Controller [USB DQ15NX6V; module 4]""
02-27 16:55:47.441 10131 10374 E RobotCore: 	at com.qualcomm.hardware.lynx.LynxModule.retransmit(LynxModule.java:1393)
02-27 16:55:47.443 10131 10374 E RobotCore: 	at com.qualcomm.hardware.lynx.commands.LynxRespondable.awaitAndRetransmit(LynxRespondable.java:365)
02-27 16:55:47.444 10131 10374 E RobotCore: 	at com.qualcomm.hardware.lynx.commands.LynxRespondable.awaitAckResponseOrNack(LynxRespondable.java:373)
02-27 16:55:47.445 10131 10374 E RobotCore: 	at com.qualcomm.hardware.lynx.commands.LynxRespondable.sendReceive(LynxRespondable.java:253)
02-27 16:55:47.446 10131 10374 E RobotCore: 	at org.openftc.revextensions2.ExpansionHubEx.getBulkInputData(ExpansionHubEx.java:440)
02-27 16:55:47.448 10131 10374 E RobotCore: 	at org.firstinspires.ftc.teamcode.Hardware_GFORCE.readEncoders(Hardware_GFORCE.java:384)
02-27 16:55:47.449 10131 10374 E RobotCore: 	at org.firstinspires.ftc.teamcode.Hardware_GFORCE.runPIDs(Hardware_GFORCE.java:726)
02-27 16:55:47.450 10131 10374 E RobotCore: 	at org.firstinspires.ftc.teamcode.TELEOP.runOpMode(TELEOP.java:143)
02-27 16:55:47.450 10131 10374 E RobotCore: 	at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper$1.run(LinearOpMode.java:305)
02-27 16:55:47.451 10131 10374 E RobotCore: 	at com.qualcomm.robotcore.util.ThreadPool.logThreadLifeCycle(ThreadPool.java:737)
02-27 16:55:47.451 10131 10374 E RobotCore: 	at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper.run(LinearOpMode.java:300)
02-27 16:55:47.453 10131 10374 E RobotCore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-27 16:55:47.454 10131 10374 E RobotCore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-27 16:55:47.454 10131 10374 E RobotCore: 	at com.qualcomm.robotcore.util.ThreadPool$ThreadFactoryImpl$1.run(ThreadPool.java:793)
02-27 16:55:47.455 10131 10374 E RobotCore: 	at java.lang.Thread.run(Thread.java:761)
02-27 16:55:47.512 10131 10220 V SoundInfo: construct(0x075715f4)
02-27 16:55:47.565 10131 10219 I MediaCodec: (0x96cdbe00) init name(audio/raw) isType(1) encoder(0)
02-27 16:55:47.570 10131 10383 I MediaCodec: (0x96cdbe00) Component Allocated (OMX.google.raw.decoder)
02-27 16:55:47.571 10131 10219 I MediaCodec: (0x96cdbe00) configure surface(0x0) crypto(0x0) flags(0)
02-27 16:55:47.571 10131 10219 D MediaCodec: (0x96cdbe00) configure format: AMessage(what = 0x00000000) = {
02-27 16:55:47.571 10131 10219 D MediaCodec:       string mime = "audio/raw"
02-27 16:55:47.571 10131 10219 D MediaCodec:       int64_t durationUs = 1043650
02-27 16:55:47.571 10131 10219 D MediaCodec:       int32_t track-id = 1
02-27 16:55:47.571 10131 10219 D MediaCodec:       int32_t channel-count = 2
02-27 16:55:47.571 10131 10219 D MediaCodec:       int32_t sample-rate = 44100
02-27 16:55:47.571 10131 10219 D MediaCodec:       int32_t channel-mask = 0
02-27 16:55:47.571 10131 10219 D MediaCodec:       int32_t pcm-encoding = 2
02-27 16:55:47.571 10131 10219 D MediaCodec:     }
02-27 16:55:47.573 10131 10219 I MediaCodec: (0x96cdbe00) start
02-27 16:55:47.580 10131 10383 I MediaCodec: (0x96cdbe00) input buffers allocated
02-27 16:55:47.580 10131 10383 I MediaCodec: (0x96cdbe00) numBuffers (4)
02-27 16:55:47.581 10131 10383 I MediaCodec: (0x96cdbe00) output buffers allocated
02-27 16:55:47.581 10131 10383 I MediaCodec: (0x96cdbe00) numBuffers (4)
02-27 16:55:47.585 10131 10383 D MediaCodec: (0x96cdbe00) [OMX.google.raw.decoder] output format changed to: AMessage(what = 0x00000000) = {
02-27 16:55:47.585 10131 10383 D MediaCodec:       string mime = "audio/raw"
02-27 16:55:47.585 10131 10383 D MediaCodec:       int32_t channel-count = 2
02-27 16:55:47.585 10131 10383 D MediaCodec:       int32_t sample-rate = 44100
02-27 16:55:47.585 10131 10383 D MediaCodec:       int32_t pcm-encoding = 2
02-27 16:55:47.585 10131 10383 D MediaCodec:       int32_t bit-width = 16
02-27 16:55:47.585 10131 10383 D MediaCodec:       int32_t channel-mask = 0
02-27 16:55:47.585 10131 10383 D MediaCodec:     }
02-27 16:55:47.606 10131 10219 I MediaCodec: (0x96cdbe00) stop
02-27 16:55:47.612 10131 10219 I MediaCodec: (0x96cdbe00) release
02-27 16:55:47.616 10131 10154 D SoundPlayer: onLoadComplete(samp=4|ms=1044, samp=4)=0
02-27 16:55:47.618 10131 10220 W AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 4, track 44100 Hz, output 48000 Hz
02-27 16:55:47.623 10131 10220 D SoundPlayer: playing volume=1.000000 samp=4|ms=1044
02-27 16:55:47.641 10131 10216 V Robocol : sending CMD_PLAY_SOUND(12862), attempt: 0
02-27 16:55:48.522 10131 10131 V FtDeviceManager: ACTION_USB_DEVICE_DETACHED: /dev/bus/usb/001/006
02-27 16:55:49.376 10131 10131 V FtDeviceManager: ACTION_USB_DEVICE_ATTACHED: /dev/bus/usb/001/007
02-27 16:55:49.376 10131 10131 V FtDeviceManager: addOrUpdateUsbDevice(vid=0x0403 pid=0x6015)
02-27 16:55:49.377 10131 10131 V FtDeviceManager: requesting permissions for device=/dev/bus/usb/001/007
02-27 16:55:49.405 10131 10131 V FtDevice: initialize(vid=0x0403 pid=0x6015 bcdDevice=0x1000)
02-27 16:55:49.405 10131 10131 V MonitoredUsbDeviceConnection: closing UsbDeviceConnection(DQ15NX6V)
02-27 16:55:49.405 10131 10131 D UsbDeviceConnectionJNI: close
02-27 16:55:49.406 10131 10131 V MonitoredUsbDeviceConnection: closing UsbDeviceConnection(DQ15NX6V)
02-27 16:55:49.406 10131 10131 D UsbDeviceConnectionJNI: close
02-27 16:55:49.406 10131 10131 V RCActivity: onPause()
02-27 16:55:49.420 10131 10131 V RCActivity: ACTION_USB_DEVICE_ATTACHED: /dev/bus/usb/001/007
02-27 16:55:49.421 10131 10229 I FtcEventLoop: vv===== MODULE ATTACH: disarm REV Robotics USB Expansion Hub Portal [DQ15NX6V]=====vv
02-27 16:55:49.421 10131 10131 V RCActivity: onResume()
02-27 16:55:49.421 10131 10229 V LynxUsb : disarmDevice() serial=DQ15NX6V...
02-27 16:55:49.422 10131 10229 V LynxUsb : ...done disarmDevice()
02-27 16:55:49.423 10131 10229 I FtcEventLoop: ======= MODULE ATTACH: arm or pretend REV Robotics USB Expansion Hub Portal [DQ15NX6V]=======
02-27 16:55:49.423 10131 10374 V RobotCore: thread: ...terminating 'LinearOpMode main'
02-27 16:55:49.426 10131 10229 V FtDeviceManager: createDeviceInfoList(): 1 USB devices
02-27 16:55:49.428 10131 10211 D RobotCore: system telemetry: key=$System$None$ msg=""
02-27 16:55:49.431 10131 10229 V FtDevice: vv********************DQ15NX6V opening********************vv 0x07f962de
02-27 16:55:49.432 10131 10229 V FtDevice: ^^********************DQ15NX6V opened ********************^^
02-27 16:55:49.432 10131 10229 V FtDevice: resetting DQ15NX6V
02-27 16:55:49.443 10131 10229 V LynxUsb : armDevice() serial=DQ15NX6V...
02-27 16:55:49.446 10131 10229 V LynxModule: pingAndQueryKnownInterfaces mod=3
02-27 16:55:49.447 10131 10413 V RobotCore: thread: 'lynx incoming datagrams' starting...
02-27 16:55:49.449 10131 10413 V LynxUsb : synchronization gained: serial=DQ15NX6V
02-27 16:55:49.452 10131 10229 V LynxModule: mod#=3 queryInterface(DEKA)=54 commands starting at 4096
02-27 16:55:49.469 10131 10229 V LynxModule: sendLEDPatternSteps(): #steps=8
02-27 16:55:49.471 10131 10217 V LynxModule: received status: LynxGetModuleStatusResponse(status=0x05 alerts=0x00: KeepAliveTimeout|FailSafe)
02-27 16:55:49.471 10131 10217 V LynxModule: resendCurrentPattern()
02-27 16:55:49.471 10131 10217 V LynxModule: sendLEDPatternSteps(): #steps=8
02-27 16:55:49.485 10131 10229 V LynxModule: pingAndQueryKnownInterfaces mod=4
02-27 16:55:49.493 10131 10229 V LynxModule: mod#=4 queryInterface(DEKA)=54 commands starting at 4096
02-27 16:55:49.509 10131 10229 V LynxModule: sendLEDPatternSteps(): #steps=10
02-27 16:55:49.513 10131 10223 V LynxModule: received status: LynxGetModuleStatusResponse(status=0x05 alerts=0x00: KeepAliveTimeout|FailSafe)
02-27 16:55:49.513 10131 10223 V LynxModule: resendCurrentPattern()
02-27 16:55:49.513 10131 10223 V LynxModule: sendLEDPatternSteps(): #steps=10
02-27 16:55:49.534 10131 10229 V LynxUsb : ...done armDevice()
02-27 16:55:49.535 10131 10229 I FtcEventLoop: ^^===== MODULE ATTACH: complete REV Robotics USB Expansion Hub Portal [DQ15NX6V]=====^^
02-27 16:55:49.535 10131 10229 E EventLoopManager: Event loop threw an exception
02-27 16:55:49.538 10131 10229 E EventLoopManager: org.openftc.revextensions2.RE2Exception: Failed to reflect on LynxController! This probably means that you're running a newer version of the SDK then I tested with and the Tech Team broke something :(
02-27 16:55:49.539 10131 10229 E EventLoopManager: 	at org.openftc.revextensions2.OpenLynxController.<init>(OpenLynxController.java:61)
02-27 16:55:49.539 10131 10229 E EventLoopManager: 	at org.openftc.revextensions2.RevBulkData.validateLynxController(RevBulkData.java:387)
02-27 16:55:49.540 10131 10229 E EventLoopManager: 	at org.openftc.revextensions2.RevBulkData.throwIfMotorInvalid(RevBulkData.java:370)
02-27 16:55:49.541 10131 10229 E EventLoopManager: 	at org.openftc.revextensions2.RevBulkData.getMotorCurrentPosition(RevBulkData.java:123)
02-27 16:55:49.541 10131 10229 E EventLoopManager: 	at org.firstinspires.ftc.teamcode.Hardware_GFORCE.readEncoder(Hardware_GFORCE.java:396)
02-27 16:55:49.542 10131 10229 E EventLoopManager: 	at org.firstinspires.ftc.teamcode.Hardware_GFORCE.getCurrentWristAngle(Hardware_GFORCE.java:986)
02-27 16:55:49.544 10131 10229 E EventLoopManager: 	at org.firstinspires.ftc.teamcode.Hardware_GFORCE.runWristPID(Hardware_GFORCE.java:1018)
02-27 16:55:49.545 10131 10229 E EventLoopManager: 	at org.firstinspires.ftc.teamcode.Hardware_GFORCE.runPIDs(Hardware_GFORCE.java:747)
02-27 16:55:49.546 10131 10229 E EventLoopManager: 	at org.firstinspires.ftc.teamcode.TELEOP.runOpMode(TELEOP.java:143)
02-27 16:55:49.546 10131 10229 E EventLoopManager: 	at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper$1.run(LinearOpMode.java:305)
02-27 16:55:49.547 10131 10229 E EventLoopManager: 	at com.qualcomm.robotcore.util.ThreadPool.logThreadLifeCycle(ThreadPool.java:737)
02-27 16:55:49.548 10131 10229 E EventLoopManager: 	at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper.run(LinearOpMode.java:300)
02-27 16:55:49.548 10131 10229 E EventLoopManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-27 16:55:49.549 10131 10229 E EventLoopManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-27 16:55:49.550 10131 10229 E EventLoopManager: 	at com.qualcomm.robotcore.util.ThreadPool$ThreadFactoryImpl$1.run(ThreadPool.java:793)
02-27 16:55:49.550 10131 10229 E EventLoopManager: 	at java.lang.Thread.run(Thread.java:761)
02-27 16:55:49.551 10131 10229 V RobotCore: RobotCoreException in EventLoopManager: EventLoop Exception in loop(): RE2Exception - Failed to reflect on LynxController! This probably means that you're running a newer version of the SDK then I tested with and the Tech Team broke something :(
02-27 16:55:49.551 10131 10229 V RobotCore: EventLoopManager state is EMERGENCY_STOP
02-27 16:55:49.552 10131 10229 V RobotCore: Robot Status: EMERGENCY STOP
02-27 16:55:49.552 10131 10229 D RobotCore: system telemetry: key=$System$Error$ msg="User code threw an uncaught exception: RE2Exception - Failed to reflect on LynxController! This probably means that you're running a newer version of the SDK then I tested with and the Tech Team broke something :("
02-27 16:55:49.553 10131 10229 I FtcEventLoop: ======= TEARDOWN =======
02

```

**Comment by Windwoes** [comment] 2019-02-28 22:00
@gearsincorg 

Hmmmm.... I have a hunch as to what's causing this. When an Expansion Hub DCs, the SDK hot-swaps in a "fake" object so that your user code doesn't crash. When sending a bulk command to the expansion hub, RE2 does a check to make sure you actually sent it to the Hub you meant to:
``` java

    /***
     * Checks to see whether a Lynx controller is attached to the Lynx
     * module that this packet came from
     *
     * @param controller the controller to validate
     *
     * @return whether or not the controller is attached to the Lynx
     *         module that this packet came from
     */
    private boolean validateLynxController(LynxController controller)
    {
        return validateLynxModule(new OpenLynxController(controller).getLynxModule());
    }
```

Notice that the constructor of OpenLynxController is invoked:

```java
    OpenLynxController(LynxController controller)
    {
        // We can get the underlying LynxModule object through a
        // LynxController object, but only through reflection.
        Method getModule_method;

        try
        {
            // The "getModule" method is located within the LynxController class
            getModule_method = LynxController.class.getDeclaredMethod("getModule");

            // Ensures the method is accessible for the next line. We still catch
            // the (impossible) IllegalAccessException just to be safe.
            getModule_method.setAccessible(true);

            // Actually get the value from the controller that was passed in.
            lynxModule = (LynxModule) getModule_method.invoke(controller);
            enhancedLynxModule = new ExpansionHubEx(lynxModule);
        }
        catch (Exception e)
        {
            throw new RE2Exception("Failed to reflect on LynxController!");
        }
}
```
So I think what's happening is that the reflection is failing on the fake object, or when the fake object is swapped for the real one again after the Expansion Hub re-connects.

Thoughts?

**Comment by Windwoes** [comment] 2019-03-01 13:29
@gearsincorg does this issue occur if you just manually unplug the USB wire to the Hub and then replug it? I want to be able to reproduce this myself.

**Comment by gearsincorg** [comment] 2019-03-05 14:33
Sorry for the late reply, I was prepping for MD State.

I have not seen this before, and I would assume I would have if it was a simple USB disconnect issue.

FWIW I have found that if the Parent Rev Hub times out, when talking to the Child Hub, the Bulk Data read returns a null pointer.  I have protected against this, by just reusing the last reply, but I wonder if this worse exception is also related to communicating with the Child hub...  

I will try specifically testing the "momentary disconnected USB" scenario. To see if I can trigger the exception.

Phil.

**Comment by Windwoes** [comment] 2019-03-05 17:59
@gearsincorg 

> FWIW I have found that if the Parent Rev Hub times out, when talking to the Child Hub, the Bulk Data read returns a null pointer.

Well, I know what causes that:

```java
    /***
     * Grab a bunch of useful data from the Lynx module in one go
     *
     * @return an object that contains a bunch of useful data
     */
    public synchronized RevBulkData getBulkInputData()
    {
        LynxGetBulkInputDataCommand command = new LynxGetBulkInputDataCommand(expansionHub);

        try
        {
            LynxGetBulkInputDataResponse response = command.sendReceive();
            return new RevBulkData(response, expansionHub);
        }

        catch (Exception e)
        {
            handleException(e);
        }

        return null;
}
```
What would you suggest instead of returning null? Making an empty object?

**Comment by Windwoes** [comment] 2019-03-05 18:43
Hmm, regarding my question of what to return instead of null, it seems the SDK's convention is just to return empty/zero. For instance:

```java
    @Override public synchronized int getMotorCurrentPosition(int motor)
        {
        this.validateMotor(motor); motor -= apiMotorFirst;
        LynxGetMotorEncoderPositionCommand command = new LynxGetMotorEncoderPositionCommand(this.getModule(), motor);
        try {
            LynxGetMotorEncoderPositionResponse response = command.sendReceive();
            return response.getPosition();
            }
        catch (InterruptedException|RuntimeException|LynxNackException e)
            {
            handleException(e);
            }
        return LynxUsbUtil.makePlaceholderValue(0);
        }
```

**Comment by gearsincorg** [comment] 2019-03-06 19:27
Once I knew this could happen, the logical action for the app to take was to ignore it, and use the last set of vales that was returned.

Should the call do this for us?  It would be safer most of the time, but it might mask an underlying hardware problem.

If you aren't going to return the last known values, then returning any other sensor value (eg zero) would be a bad idea.  In this case, returning a null is a reasonable way to alert the user there is a problem, and they need to handle it.  

Of course I discovered the problem when I tried to access the actual encoder value using the null bulk data object.

**Comment by Windwoes** [comment] 2019-03-06 21:49
@gearsincorg 

> If you aren't going to return the last known values, then returning any other sensor value (eg zero) would be a bad idea. In this case, returning a null is a reasonable way to alert the user there is a problem, and they need to handle it.

I think I agree with that - but the SDK currently does not follow that convention - and I'd like to be consistent with the SDK..... perhaps you could suggest to Bob / Tom to change the SDK's convention?

**Comment by gearsincorg** [comment] 2019-03-07 12:20
I'm not sure what I'd be suggesting actually...   (I'm not that savvy with the lower levels of the SDK)

My original post was just letting you know about an anomaly I encountered.  At this point, I'm just looking to recover from REVExtensions2 throwing an exception if I get a momentary (rareish) comms loss.

**Comment by Windwoes** [comment] 2019-03-07 13:02
OK. I'll mess around with my robot today and see if I can reproduce the issue you're seeing.

**Comment by Windwoes** [comment] 2019-03-16 14:10
@gearsincorg until I fix this, perhaps just wrapping the call in try/catch would be a temporary workaround for you?

**Comment by gearsincorg** [comment] 2019-03-30 12:25
Yeah... that's kinda where I came into this issue.  I was looking for a recommendation as to how to recover from the exception.

ie: What is a reasonable recovery action to be taken in the catch?  Is there any value in just ignoring the error that one time, and hoping for it to recover, or do some objects need to be recreated?

**Comment by Windwoes** [comment] 2019-03-31 00:28
Hmm. That is an interesting question regarding object re-instantiation, because if the SDK recreates the LynxModule object that the ExpansionHubEx object holds a reference to, then even if the SDK recovers, any RE2 calls would still fail. Hopefully I will be able to do some testing next week and find some answers...

**Comment by Windwoes** [comment] 2019-04-05 23:05
@gearsincorg I did some testing today and I was not able to reproduce the issue you're seeing :( it seems to survive any type of disconnect whether it be USB, power, or 485. Speaking of 485, I did find a bug in the SDK actually.... if the 485 wire is disconnected for more than the 2.5s timeout and then reconnected while the opmode is running, the Hub communicates properly with the SDK again, but the SDK does not re-send the LED sequence command, so although it is working properly it shows the "disconnected" LED pattern, lol.

**Comment by gearsincorg** [comment] 2019-04-06 12:06
I guess the good news is that it appears to be a low probability error, although the bad news is that it's still out there, waiting to throw an exception.

If it is just a transient problem, then I suppose catching it may keep the App running.

I appreciate your help.

**Comment by Windwoes** [comment] 2019-04-06 13:13
Do you have any info on what the circumstances were up to the point where the exception was thrown? (e.g. brown-out from 12v, ESD)?

I'd really like to get to the bottom of this because I'm going to be running RE2 on our bot in Detroit....

**Comment by gearsincorg** [comment] 2019-04-06 13:44
History:

The error occurred while deploying from the lander during driver practice in our facility.
Our hardware and electrical is pretty robust, with good cable restraint and shielding for the wiring.  

Recently however, (days prior) we had been getting occasional issues from RE2, but they were less disruptive as they were easily detected (readBulkData returning a null object).  These errors had been coinciding with latencies caused by coms timeouts between the two expansion hubs.  We had decided that we were getting intermittent issues on the RS485 bus, possibly due to loose connector terminals.  We had essentially eliminated the problem by running a pair of redundant cables between the two hubs using both of the RS485 terminals on each hub (the RS485 terminals are simply wired in parallel on the PCB).

This wiring change had eliminated the timeouts and so we felt we had fully addresses the issue, until this new exception during Auto.

It has never recurred, but from the log on my first post you can see that it definitely coincides with a recovering coms disruption.  Possibly ESD, or just simple mechanical.

**Comment by Windwoes** [comment] 2019-04-06 14:07
Hmm, interesting. Now, just to throw it out there, in one of my tests where I pulled the 485 wire during a live OpMode, I got a StuckInLoop() error, which seems to me to be the fault of the SDK rather than RE2. I was very careful when implementing all of RE2's commands to follow the exact error-handling structure that the SDK uses.

**Comment by Windwoes** [comment] 2019-04-06 23:41
Hmm I think I see what caused the issue. If the `isHooked` boolean in LynxController is false, then `getModule()` returns `pretendModule`, causing the cast to LynxModule in OpenLynxController to fail....

**Comment by Windwoes** [comment] 2019-04-07 02:12
Which then begs the question.... why *wouldn't* `isHooked` be false when a DC occurs?

**Comment by Windwoes** [comment] 2019-07-07 00:24
@gearsincorg Ok I'm 99% sure I've fixed the possibility for this bug to ever happen in [this](https://github.com/OpenFTC/RevExtensions2/commit/8cf49ea8a25e1a63e77d8b490fab3fabdaee9b68) commit.

**Comment by gearsincorg** [comment] 2019-07-07 13:19
OK, I'll Load this in the first chance I get.  It may be a while...

**Comment by Windwoes** [comment] 2019-07-07 13:24
@gearsincorg Well, it will be difficult for you to test it out until I push a new release to Bintray, but if you feel so inclined you could test it by manually copying in the source code files.

**Comment by Windwoes** [comment] 2019-07-07 13:27
I'm going to try to push a new release to Bintray shortly, though.

**Comment by Windwoes** [comment] 2019-07-28 23:15
v1.2 has been released, which includes the fix for this issue

**Closed as completed by Windwoes** 2019-07-28 23:15 UTC
